version: "3"
services:
  sonarqube:
    image: "sonarqube:lts"
    container_name: "sonarqube-LTS"
    ports:
      # local port:docker port
      - "9000:9000"
    volumes:
      # local volume:docker volume
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    networks:
      - sonar-network
  db:
    image: "postgres:11"
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    networks:
      - sonar-network

networks:
  sonar-network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgres:
  postgres_data:
