version: "3.7"
services:
  jenkins-master:
    # original
    #image: "jenkins/jenkins:lts-jdk11"
    # custom
    image: "demo/jenkins.lts-jdk11:2020-02-28.2943"
    ports:
      - target: 8080 # docker port
        published: 8080 # published port
        protocol: tcp
        mode: host
      - target: 8443 # docker port
        published: 8443 # published port
        protocol: tcp
        mode: host
      # access to a remote Java (JIRA) API
      - target: 50000 # docker port
        published: 50000 # published port
        protocol: tcp
        mode: host
    volumes:
      # global named volume:docker volume
      - jenkins_master:/var/jenkins_home
      # for unix instead of DOCKER_HOST
      - /var/run/docker.sock:/var/run/docker.sock
      # private ssh key for agent (slaves)
      - ./agent-ssh-key/id_rsa:/tmp/jenkinsAgent_rsa:ro
    env_file: .env
    environment:
      # Start jenkins unlocked - skip wizard with users creation
      - JAVA_OPTS=-server -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -Djenkins.install.runSetupWizard=false
      # for windows you have to enable "Expose daemon on tcp://localhost:2375 without TLS" in Docker settings
      #- DOCKER_HOST=tcp://host.docker.internal:2375
      - CREDENTIALS_GITHUB_USERNAME=${CREDENTIALS_GITHUB_USERNAME}
      - CREDENTIALS_GITHUB_PASSWORD=${CREDENTIALS_GITHUB_PASSWORD}
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.75'
          memory: 2.5G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        name: "jenkins-master"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 2m30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - default
      - backend
    user: jenkins

  jenkins-slave:
    image: "jenkins/ssh-slave:jdk11"
    volumes:
      - jenkins_slave:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbcN+HUA16PoKWVozN6IByCtBh+UyaMU4xFS1extgX5sdrUMfWkK1fMkF/N1ZUyAjsHIg1k2YFgSgZUBDuxs1ykhjfBdRm7KHKnvsFYUoQBYzgj/sX4rToK3MacFJGDMuYZr/UcrRVRc/EVWivX4WGQHejCggit6xlYY12eJGoS5VHw6cXicaRuNjB9n4op6m+E6S/QbMk9JOMQpfNU/BZamRE99IiKYk96C3tDgCdJTmzaKcI01OZjiUJGmTiOPuR+pQFc21Drf9K+PG6NkugqSxDg1Ya7KQOIaaaKFjKbWMoiz5Uybmj5jAVkSQxlST51dAq6Xr/aIoWD1zgAAQGh+vRuS4M570poTaxKi2DM/10V1KJXv3bHVRx28Iq6m0QaRFQ+n9bCNo+nf5sTDYnL7NK9AMZPMQLKQbxwTRKfceoXXADvDR8BSK78eWzipLGE+Y8o9qrw2HzcWGmk3YDy/rIiWRU59cVIsRab/qNCSll/0AP9JIxOcw+uHPX8xzUyri62mPdpeLsMioPEHz39VbslFGsANcv5OPLWrvUe8laX9wvSNGXaVRR+0A2FY/dqsJnVZlKo8+a9V5PogC0ojiibjxrVrXVJOKJAS0QPVtAYB12vBgO6/8wytfrZ4Ql6YcwFmFTZxuvfRskf6kU7jQr6jBr68jsH78bfzOmXw== jenkinsAgent
    deploy:
      replicas: 0
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.50'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        name: "jenkins-slave"
    networks:
      - backend
    user: root

networks:
  default:
    # name of network created first by create-network.sh or create-swarm-network.sh script
    name: demo-swarm
    external: true
  backend:
    driver: overlay

volumes:
  jenkins_master:
  jenkins_slave:
