version: "3"
services:
  postgres:
    image: "postgres:11"
    container_name: "pg11"
    ports:
      # local port:docker port
      - "5432:5432"
    volumes:
      # local volume:docker volume
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
  postgres_data:
