version: "3.7"
services:
  postgres:
    image: "postgres:12"
    ports:
      - target: 5432 # docker port
        published: 5432 # published port
        protocol: tcp
        mode: host
    volumes:
      # global named volume:docker volume
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.50'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        name: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - default

networks:
  default:
    # name of network created first by create-network.sh or create-swarm-network.sh script
    name: demo-swarm
    external: true

volumes:
  postgres:
  postgres_data:
