version: "3.7"
services:
  nexus:
    image: "sonatype/nexus:oss"
    ports:
      - target: 8081 # docker port
        published: 8081 # published port
        protocol: tcp
        mode: host
    volumes:
      # global named volume:docker volume
      - nexus_data:/sonatype-work
    environment:
      - CONTEXT_PATH=/nexus
      - MIN_HEAP=256m
      - MAX_HEAP=768m
      - JAVA_OPTS=-server -XX:MaxPermSize=192m -Djava.net.preferIPv4Stack=true
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.50'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        name: "nexus"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/nexus"]
      interval: 2m30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - default

networks:
  default:
    # name of network created first by create-network.sh or create-swarm-network.sh script
    name: demo-swarm
    external: true

volumes:
  nexus_data:
